"""estrutura inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 13:05:27.013651
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=30), nullable=True),
    sa.Column('contato', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_nome_normalizado'), 'fornecedores', ['nome_normalizado'], unique=True)
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=100), nullable=False),
    sa.Column('perfil', sa.Enum('admin', 'usuario', name='perfil_usuario'), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_nome', sa.String(length=200), nullable=True),
    sa.Column('data_recebimento', sa.Date(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('cnpj', sa.String(length=30), nullable=True),
    sa.Column('contato', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('numero', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Enum('recebida', 'em_analise', 'aprovada', 'recusada', name='status_registro'), server_default='recebida', nullable=False),
    sa.Column('condicao_pagamento', sa.String(length=200), nullable=True),
    sa.Column('prazo_entrega', sa.String(length=200), nullable=True),
    sa.Column('frete', sa.Enum('CIF', 'FOB', name='tipo_frete'), nullable=True),
    sa.Column('valor_frete', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('referencia_interna', sa.String(length=120), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('busca', sa.Text(), server_default='', nullable=False),
    sa.Column('importacao_ref', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('importacao_ref')
    )
    op.create_index(op.f('ix_registros_data_recebimento'), 'registros', ['data_recebimento'], unique=False)
    op.create_index(op.f('ix_registros_fornecedor_id'), 'registros', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_registros_status'), 'registros', ['status'], unique=False)
    op.create_index(op.f('ix_registros_unidade_id'), 'registros', ['unidade_id'], unique=False)
    op.create_table('uso_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_entrada', sa.String(length=20), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=False),
    sa.Column('tokens_saida', sa.Integer(), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uso_ia_criado_em'), 'uso_ia', ['criado_em'], unique=False)
    op.create_index(op.f('ix_uso_ia_unidade_id'), 'uso_ia', ['unidade_id'], unique=False)
    op.create_index(op.f('ix_uso_ia_usuario_id'), 'uso_ia', ['usuario_id'], unique=False)
    op.create_table('itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(length=300), nullable=False),
    sa.Column('produto_normalizado', sa.String(length=300), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('unidade_medida', sa.String(length=20), server_default='', nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['registro_id'], ['registros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_produto_normalizado'), 'itens', ['produto_normalizado'], unique=False)
    op.create_index(op.f('ix_itens_registro_id'), 'itens', ['registro_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_registro_id'), table_name='itens')
    op.drop_index(op.f('ix_itens_produto_normalizado'), table_name='itens')
    op.drop_table('itens')
    op.drop_index(op.f('ix_uso_ia_usuario_id'), table_name='uso_ia')
    op.drop_index(op.f('ix_uso_ia_unidade_id'), table_name='uso_ia')
    op.drop_index(op.f('ix_uso_ia_criado_em'), table_name='uso_ia')
    op.drop_table('uso_ia')
    op.drop_index(op.f('ix_registros_unidade_id'), table_name='registros')
    op.drop_index(op.f('ix_registros_status'), table_name='registros')
    op.drop_index(op.f('ix_registros_fornecedor_id'), table_name='registros')
    op.drop_index(op.f('ix_registros_data_recebimento'), table_name='registros')
    op.drop_table('registros')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('unidades')
    op.drop_index(op.f('ix_fornecedores_nome_normalizado'), table_name='fornecedores')
    op.drop_table('fornecedores')
    for enum in ('status_registro', 'tipo_frete', 'perfil_usuario'):
        sa.Enum(name=enum).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
